-keep class com.riqel.cybertool.** { *; }
-keepclassmembers class * extends android.app.Activity { *; }
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
